# Generated by Django 4.2.10 on 2024-02-20 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0003_alter_order_options_order_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='code',
            new_name='customer_code',
        ),
    ]
