# Generated by Django 4.2.10 on 2024-02-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0004_rename_code_customer_customer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='+254XXXXXXXXX', max_length=13),
        ),
    ]
