name: DjangoREST CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pipenv
        pipenv install --dev

    - name: Run tests with pytest and coverage
      run: |
        pipenv run pytest --cov=./

    - name: Deploy to Render
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        pipenv install render-cli
        ./build.sh
