name: Django CI/CD

on:
  push:
    branches:
      - main  # or the branch you want to trigger CI/CD for

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pipenv
        pipenv install --dev 

    - name: Run tests
      run: |
        pipenv run python manage.py test

    - name: Build and deploy (replace with your deployment steps)
      run: |
        # Add your deployment steps here
        # For example, deploying to a server or a cloud platform
